Pvayladev 691 hotfix execlisting package list
ria-ee/X-Road pull request #1
Opened 2017-02-10 12:23 UTC by skallio

2017-02-10 12:50 UTC, jansu76 approved these changes
Looks fine to me

2017-02-10 12:53 UTC, iluwatar approved these changes

2017-02-10 13:21 UTC, VitaliStupin requested changes
build process ended with:

parsechangelog/debian: warning:     debian/changelog(l3): badly formatted heading line
LINE: * PVAYLADEV-691: Hotfix for ExecListingSensor init. (Fixes package listing information, etc)
parsechangelog/debian: warning:     debian/changelog(l5): badly formatted heading line
LINE: -- Sami Kallio <sami.kallio@gofore.com> Fri, 10 FebJan 2017 14:05:11 +0200
parsechangelog/debian: warning:     debian/changelog(l8): found start of entry where expected start of change data
LINE: xroad (6.9.2) trusty; urgency=low
parsechangelog/debian: warning:     debian/changelog(l8): found eof where expected start of change data
dpkg-buildpackage: error: unable to determine source changed by
dpkg-buildpackage: source package xroad
dpkg-buildpackage: source version 6.9.3
dpkg-buildpackage: source distribution trusty Build step 'Execute shell' marked build as failure

2017-02-10 13:27 UTC, VitaliStupin commented
You should add missing spaces to the:
https://github.com/vrk-kpa/X-Road/blob/PVAYLADEV-691-hotfix-execlisting-package-list/xtee6/packages/xroad/debian/changelog

2017-02-10 15:27 UTC, VitaliStupin approved these changes

2017-02-13 07:11 UTC, iluwatar commented on xtee6/packages/xroad-jetty9/debian/changelog
> + -- Sami Kallio <sami.kallio@gofore.com> Fri, 10 FebJan 2017 14:05:11 +0200
LINE:  -- Sami Kallio <sami.kallio@gofore.com> Fri, 10 FebJan 2017 14:05:11 +0200
parsechangelog/debian: warning: xroad-jetty9/debian/changelog(l5): couldn't parse date Fri, 10 FebJan 2017 14:05:11 +0200

2017-02-13 08:31 UTC, VitaliStupin commented on xtee6/build_packages.sh
> +#./compile_code.sh "$@"
This does not feel right. We need to compile the code before packaging.

2017-02-13 13:00 UTC, iluwatar commented on xtee6/packages/xroad-jetty9/debian/changelog
> + * Version bump
Packaging still warns about this line.

parsechangelog/debian: warning:     debian/changelog(l3): unrecognized line
LINE:  * Version bump 
parsechangelog/debian: warning:     debian/changelog(l5): found trailer where expected start of change data
LINE:  -- Sami Kallio <sami.kallio@gofore.com>  Mon, 13 Feb 2017 10:24:15 +0200

Needs one additional space, I think.

2017-02-13 13:07 UTC, merged