Estonian 6.12.0: XTE-99, XTE-252, XTE-293, XTE-294, XTE-307, XTE-308, XTE-310, XTE-333
ria-ee/X-Road pull request #17
Opened 2017-03-16 17:17 UTC by kristoheero

* XTE-99 / Joint development issue #79: Security Server UI: Added uniqueness check of the entered security server code when initializing the server.
* XTE-252 / Joint development issue #53: Security Server: Upgraded embedded Jetty to the version 9.4.2. Due to upgrade SHA1 ciphers are no longer supported for communication between security server and client.
* XTE-293: Security Server: A field set used to generate the token ID of the SSCD has been made configurable.
* XTE-294 / Joint development issue #84: Security Server: Added configuration file for the OCSP responder Jetty server (and increased max threads size of the thread pool).
* XTE-307 / Joint development issue #131: Security Server bugfix: Added missing HTTP header "Connection: close" into the server proxy response in cases error occurs before parsing a service provider's response.
* XTE-308 / Joint development issue #132: Security Server bugfix: Added missing read timeout for OCSP responder client.
* XTE-310 / Joint development issue #125: Security Server bugfix: SOAP messages with attachments caused in some cases a temopray file handle leak.
* XTE-333 / Joint development issue #128: Security Server bugfix: Fixed parsing SOAP messages containing & or < entities.
* Security Server: TCP socket SO_LINGER values in the proxy configuration file (proxy.ini) set to -1 according to avoid unexpected data stream closures.

Also updated documents:

* IG-SS
* UG-SYSPAR

2017-03-17 09:28 UTC, VitaliStupin approved these changes

2017-03-17 12:11 UTC, jhyoty commented
Regarding XTE-333 / JD#128:
The issue is fixed, but another problem is introduced by adding a dependency to Apache Xerces 2.11.0. This library is quite old (released in 2010) and a newer version is not available; the project itself does not seem to be active any more. Xerces version 2.11.0 contains at least one security vulnerability (CVE-2013-4002, [2]) which is patched in the JDK's bundled SAX implementation (a fork of Xerces) [2]. 

[1] https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2013-4002
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1019176

2017-03-17 13:34 UTC, iluwatar requested changes
We request changes because of reasons described by @jhyoty. It is unacceptable to introduce a new dependency to Apache Xerces component which has known vulnerabilities and is not anymore actively maintained.

2017-03-20 07:36 UTC, kristoheero commented
JDK xerces version is 2.8.1 and there does not work necessary feature http://apache.org/xml/features/scanner/notify-char-refs (see https://xerces.apache.org/xerces2-j/features.html#scanner.notify-char-refs). Without that it is very difficult to achieve effective replacement of ampersand characters.

We can use xerces  JBoss fork 2.11.1 https://github.com/jboss/xerces (https://mvnrepository.com/artifact/xerces/xercesImpl/2.11.0.SP5) which seems to be fixed:

CVE-2013-4002 fix in 2.11.0.SP5 repository:
https://github.com/jboss/xerces/commit/824683a9e2d4d3c0989128468707925bfeb701c7

2017-03-20 11:18 UTC, iluwatar commented
@kristoheero utilizing the JBoss Xerces fork instead is an acceptable solution. Please commit the changes and we will test it.

2017-03-20 14:34 UTC, kristoheero commented
@iluwatar Xerces updated.

2017-03-21 09:15 UTC, jhyoty commented
We found one more issue. The SAX XML parser writer component seems to strip comments from the message (e.g., a `<!-- comment -->` is removed from response messages). This is yet another bug since the old parser kept comments and comments are part of the XML information set.

2017-03-21 12:41 UTC, kristoheero commented
@jhyoty Comments issue fixed.

2017-03-23 08:52 UTC, iluwatar commented
@kristoheero according to https://github.com/ria-ee/X-Road/pull/14#issuecomment-286996058 `src/common-util/src/main/java/ee/ria/xroad/common/util/AbstractHttpSender.java` is needed for the https://github.com/vrk-kpa/xroad-joint-development/issues/128 fix. Can you comment why it was needed to change the method [AbstractHttpSender#streamClosed](https://github.com/ria-ee/X-Road/pull/17/files#diff-90f5f0cb03654959dad9a01c23f0a541R271) implementation?

2017-03-23 09:53 UTC, kristoheero commented
@iluwatar Implementation change of the method _AbstractHttpSender#streamClosed_ is caused by a new version of **xerces** library. If the SAX parser throws an exception the input stream is now closed. And we hide this original exception if we throw own exception in the method _streamClosed()_ .

2017-03-30 09:18 UTC, iluwatar approved these changes

2017-03-30 09:22 UTC, iluwatar commented
In the future it would be helpful if the commits would not be squashed. At least not so that multiple features are squashed into single commit. Otherwise it is very hard to review changes and cherry pick features.

2017-03-30 09:24 UTC, merged