Optional HSM slot index configuration
ria-ee/X-Road pull request #60
Opened 2017-09-14 08:28 UTC by zpotoloom

Implements https://github.com/vrk-kpa/xroad-joint-development/issues/177

2017-09-14 09:48 UTC, VitaliStupin commented on doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
> +Version: 3.0
2.10 would be a better version

2017-09-14 09:48 UTC, VitaliStupin commented on doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
> +To prevent scanning a lot of unnecessary slots specific slot indexes can be configured in `/etc/xroad/conf.d/signer.ini`
signer.ini should not be modified by end user. /etc/xroad/conf.d/local.ini should be used instead

2017-09-14 09:51 UTC, VitaliStupin commented on src/packages/default-configuration/signer.ini
> +;hsm-slot-indexes=0,7,12
There is no need to put this parameter to signer.ini. End users should add that to local.ini manually.

2017-09-19 12:33 UTC, VitaliStupin commented on doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
> +`[signer]
Visual bug. All lines are collapsed into one line in github.

2017-09-19 13:41 UTC, VitaliStupin approved these changes

2017-09-20 09:09 UTC, jhyoty requested changes

2017-09-20 09:09 UTC, jhyoty commented on src/addons/hwtoken/src/main/java/ee/ria/xroad/signer/tokenmanager/module/HardwareModuleWorker.java
> +        if (hsmSlots[0] == "") {
Strings should not be compared using reference equality. Preferably, getHSMSlotIndexes should return a zero-length array if the property is not set.

2017-09-20 09:09 UTC, jhyoty commented on src/addons/hwtoken/src/main/java/ee/ria/xroad/signer/tokenmanager/module/HardwareModuleWorker.java
> +                if (hsmSlots[i].matches("\\d+")) {
It probably should be an error if an index is not a positive integer, or is larger than the number of slots. Note that parseInt throws NumberFormatException if the value exceeds Integer.MAX_VALUE.

2017-09-20 09:09 UTC, jhyoty commented on src/addons/hwtoken/src/main/java/ee/ria/xroad/signer/tokenmanager/module/HardwareModuleWorker.java
> +                            log.info("Module '{}' slot #{} has token with ID '{}' "
Maybe it should be an error if the list of indexes contains duplicates?

2017-09-20 09:09 UTC, jhyoty commented on src/common-util/src/main/java/ee/ria/xroad/common/SystemProperties.java
> +        return System.getProperty(HSM_SLOT_INDEXES, "").split(",");
Consider returning an empty (zero-length) array or list if the property does not exist (or is an empty string).

2017-09-20 16:13 UTC, zpotoloom commented on src/addons/hwtoken/src/main/java/ee/ria/xroad/signer/tokenmanager/module/HardwareModuleWorker.java
> +                if (hsmSlots[i].matches("\\d+")) {
Currently most of the uses of parseInt from String are not checked for invalid values. Should be added globally.

2017-09-21 05:05 UTC, jhyoty commented on src/addons/hwtoken/src/main/java/ee/ria/xroad/signer/tokenmanager/module/HardwareModuleWorker.java
> +                if (hsmSlots[i].matches("\\d+")) {
Here, some invalid values are ignored and skipped, where others (too large for an int) will throw an exception and stop the processing. This is inconsistent, the check should either skip all invalid values or an exception should be thrown.

2017-09-22 09:57 UTC, jhyoty commented on src/addons/hwtoken/src/main/java/ee/ria/xroad/signer/tokenmanager/module/HardwareModuleWorker.java
> +                if (hsmSlots[i].matches("\\d+")) {
Some invalid values are ignored and skipped, where others (too large for an int) will throw an exception and stop the processing. This is inconsistent, the check should either skip all invalid values or an exception should be thrown.

2017-10-09 10:33 UTC, jhyoty commented
@zpotoloom, this PR needs updating. It has a merge conflict and some requested changes.

2017-11-08 16:55 UTC, closed without merging