EU RDF SF logos attached
ria-ee/X-Road pull request #66
Opened 2017-11-23 14:59 UTC by ToomasMolder

2017-11-27 07:55 UTC, iluwatar commented
Pull request name and description are not following the workflow. See workflow chapter 9.1 https://github.com/vrk-kpa/xroad-joint-development/blob/master/WORKFLOW.md#9-pull-requests

2017-11-27 09:01 UTC, VitaliStupin requested changes

2017-11-27 09:01 UTC, VitaliStupin commented on doc/Architecture/arc-g_x-road_arhitecture.md
> +# X-Road Architecture
Should be:
# X-Road Architecture
**Technical Specification**

2017-11-27 09:01 UTC, VitaliStupin commented on doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
> +# X-ROAD 6
No need for double header. Could be "X-ROAD 6 Security Server Installation Guide" instead, or could be left unchanged

2017-11-27 09:01 UTC, VitaliStupin commented on doc/Architecture/arc-ss_x-road_security_server_architecture.md
> +# Technical Specification
"Technical Specification" should not be header.

2017-11-27 09:01 UTC, VitaliStupin commented on doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
> +# X-ROAD 6
double header

2017-11-27 09:01 UTC, VitaliStupin commented on doc/OperationalMonitoring/Protocols/pr-opmonjmx_x-road_operational_monitoring_jmx_protocol_Y-1096-3.md
> +# Technical Specification
double header

2017-11-27 09:01 UTC, VitaliStupin commented on doc/OperationalMonitoring/Protocols/pr-opmon_x-road_operational_monitoring_protocol_Y-1096-2.md
> +# Technical Specification
double header

2017-11-27 09:01 UTC, VitaliStupin commented on doc/UseCases/uc-mess_x-road_member_communication_use_case_model.md
> +# Analysis
double header

2017-11-27 09:50 UTC, ToomasMolder commented
Estonian-6.17.0-2: EU RDF SF logos attached

2017-11-28 07:14 UTC, VitaliStupin approved these changes

2017-11-28 08:16 UTC, iluwatar approved these changes

2017-11-28 08:16 UTC, merged